// Datos de ejemplo para el Modo Demo.
//
// Estas ofertas son ficticias. Los nombres de empresas son de compañías conocidas
// de Argentina y se usan como referencia ilustrativa únicamente.
// NO representan ofertas reales ni exponen información personal del propietario.

import { Oferta, Estadisticas } from '../modelos/oferta.model';

export const OFERTAS_DEMO: Oferta[] = [

    // ─── APROBADAS (10) ───────────────────────────────────────────────────────

    {
        id: 1001,
        titulo: 'Desarrollador Frontend Angular Jr.',
        empresa: 'MercadoPago',
        ubicacion: 'Buenos Aires, Argentina',
        modalidad: 'remoto',
        descripcion: 'Buscamos un Frontend Developer Jr. con conocimiento en Angular 17+, TypeScript y RxJS. Trabajo en equipo ágil (Scrum). Se valoran buenas prácticas, testing unitario y comunicación.',
        url: 'https://www.linkedin.com/jobs/view/1001',
        plataforma: 'linkedin',
        nivel_requerido: 'junior',
        salario_min: '600000',
        salario_max: '900000',
        moneda: 'ARS',
        estado_evaluacion: 'aprobada',
        razon_evaluacion: 'Excelente match: Angular y TypeScript están en el stack del candidato. Nivel junior requerido alineado con el perfil trainee/junior.',
        porcentaje_match: 91,
        estado_postulacion: 'no_postulado',
        fecha_publicacion: '2026-04-01T10:00:00.000Z',
        fecha_extraccion: '2026-04-02T08:00:00.000Z',
        datos_crudos: null,
    },
    {
        id: 1002,
        titulo: 'QA Tester Jr. (Manual + Automatización)',
        empresa: 'Globant',
        ubicacion: 'Buenos Aires, Argentina',
        modalidad: 'híbrido',
        descripcion: 'Posición junior para QA. Se valorará experiencia en testing manual, escritura de casos de prueba, Selenium y conocimientos básicos de SQL para validar datos.',
        url: 'https://www.computrabajo.com.ar/ofertas-de-trabajo/oferta-1002',
        plataforma: 'computrabajo',
        nivel_requerido: 'junior',
        salario_min: null,
        salario_max: null,
        moneda: null,
        estado_evaluacion: 'aprobada',
        razon_evaluacion: 'QA Testing es uno de los perfiles fuertes del candidato. Testing manual y automatización coinciden con su experiencia. Nivel junior apropiado.',
        porcentaje_match: 87,
        estado_postulacion: 'no_postulado',
        fecha_publicacion: '2026-04-01T09:00:00.000Z',
        fecha_extraccion: '2026-04-02T08:00:00.000Z',
        datos_crudos: null,
    },
    {
        id: 1003,
        titulo: 'Frontend Developer — Angular / React',
        empresa: 'Despegar',
        ubicacion: 'Buenos Aires, Argentina',
        modalidad: 'remoto',
        descripcion: 'Desarrollador Frontend Jr./Semi-Jr. para trabajo en sistemas de reservas y experiencia de usuario. Stack: Angular o React, TypeScript, REST APIs. Se provee mentoreo.',
        url: 'https://www.linkedin.com/jobs/view/1003',
        plataforma: 'linkedin',
        nivel_requerido: 'junior',
        salario_min: '700000',
        salario_max: '1000000',
        moneda: 'ARS',
        estado_evaluacion: 'aprobada',
        razon_evaluacion: 'Angular y React están en el stack del candidato. Nivel requerido compatible con su perfil trainee/junior.',
        porcentaje_match: 84,
        estado_postulacion: 'no_postulado',
        fecha_publicacion: '2026-03-31T14:00:00.000Z',
        fecha_extraccion: '2026-04-02T08:00:00.000Z',
        datos_crudos: null,
    },
    {
        id: 1004,
        titulo: 'Desarrollador Full Stack Jr. (Node.js + Angular)',
        empresa: 'Ualá',
        ubicacion: 'Buenos Aires, Argentina',
        modalidad: 'remoto',
        descripcion: 'Buscamos Full Stack Jr. para equipo de fintech. Conocimientos en Node.js, Express, Angular y PostgreSQL. Trabajo en sprints cortos y cultura de feedback continuo.',
        url: 'https://www.linkedin.com/jobs/view/1004',
        plataforma: 'linkedin',
        nivel_requerido: 'junior',
        salario_min: null,
        salario_max: null,
        moneda: null,
        estado_evaluacion: 'aprobada',
        razon_evaluacion: 'Stack exactamente alineado: Node.js, Express, Angular y PostgreSQL son todas tecnologías conocidas por el candidato.',
        porcentaje_match: 82,
        estado_postulacion: 'no_postulado',
        fecha_publicacion: '2026-03-30T11:00:00.000Z',
        fecha_extraccion: '2026-04-02T08:00:00.000Z',
        datos_crudos: null,
    },
    {
        id: 1005,
        titulo: 'Analista QA Jr. (Manual / Selenium)',
        empresa: 'Accenture Argentina',
        ubicacion: 'Buenos Aires, Argentina',
        modalidad: 'híbrido',
        descripcion: 'Analista QA Jr. para proyectos de banca digital. Escritura de casos de prueba, testing manual, regresión y SQL básico para validación de datos.',
        url: 'https://ar.indeed.com/viewjob?jk=1005',
        plataforma: 'indeed',
        nivel_requerido: 'trainee',
        salario_min: '550000',
        salario_max: '750000',
        moneda: 'ARS',
        estado_evaluacion: 'aprobada',
        razon_evaluacion: 'Perfil QA junior compatible. SQL básico y testing manual coinciden con la experiencia del candidato. Entorno bancario es IT/tecnología compatible.',
        porcentaje_match: 79,
        estado_postulacion: 'no_postulado',
        fecha_publicacion: '2026-04-01T08:00:00.000Z',
        fecha_extraccion: '2026-04-02T08:00:00.000Z',
        datos_crudos: null,
    },
    {
        id: 1006,
        titulo: 'Desarrollador .NET Jr.',
        empresa: 'Oracle Argentina',
        ubicacion: 'CABA, Argentina',
        modalidad: 'presencial',
        descripcion: 'Desarrollador .NET Jr. para sistemas internos de gestión. C#, ASP.NET, SQL Server. Se valora conocimiento de patrones REST y trabajo con APIs.',
        url: 'https://www.bumeran.com.ar/empleos/oferta/1006',
        plataforma: 'bumeran',
        nivel_requerido: 'junior',
        salario_min: null,
        salario_max: null,
        moneda: null,
        estado_evaluacion: 'aprobada',
        razon_evaluacion: 'C#, ASP.NET y SQL Server están en el stack del candidato. Nivel junior apropiado para el rol.',
        porcentaje_match: 78,
        estado_postulacion: 'no_postulado',
        fecha_publicacion: '2026-03-29T10:00:00.000Z',
        fecha_extraccion: '2026-04-02T08:00:00.000Z',
        datos_crudos: null,
    },
    {
        id: 1007,
        titulo: 'Frontend Developer Trainee (Angular)',
        empresa: 'Nubi',
        ubicacion: 'Buenos Aires, Argentina',
        modalidad: 'remoto',
        descripcion: 'Primera experiencia laboral en Frontend. Capacitación interna, mentoreo semanal y pair programming. Conocimientos básicos de HTML5, CSS3 y Angular suficientes para postular.',
        url: 'https://www.getonbrd.com/jobs/1007',
        plataforma: 'getonbrd',
        nivel_requerido: 'trainee',
        salario_min: '400000',
        salario_max: '600000',
        moneda: 'ARS',
        estado_evaluacion: 'aprobada',
        razon_evaluacion: 'Trainee Angular con mentoreo: ideal para el nivel del candidato. Stack exactamente alineado. Modalidad remoto es preferida.',
        porcentaje_match: 75,
        estado_postulacion: 'no_postulado',
        fecha_publicacion: '2026-04-02T09:00:00.000Z',
        fecha_extraccion: '2026-04-02T08:00:00.000Z',
        datos_crudos: null,
    },
    {
        id: 1008,
        titulo: 'Desarrollador Web Jr. (HTML/CSS/TypeScript)',
        empresa: 'Naranja X',
        ubicacion: 'Córdoba / Remoto',
        modalidad: 'híbrido',
        descripcion: 'Buscamos desarrollador web Jr. con base sólida en HTML5, CSS3, JavaScript y TypeScript. Plus si conoce React. Equipo joven y cultura de crecimiento.',
        url: 'https://www.linkedin.com/jobs/view/1008',
        plataforma: 'linkedin',
        nivel_requerido: 'junior',
        salario_min: null,
        salario_max: null,
        moneda: null,
        estado_evaluacion: 'aprobada',
        razon_evaluacion: 'HTML, CSS, JavaScript y TypeScript cubren el núcleo del stack del candidato. Nivel junior compatible.',
        porcentaje_match: 73,
        estado_postulacion: 'no_postulado',
        fecha_publicacion: '2026-03-28T15:00:00.000Z',
        fecha_extraccion: '2026-04-02T08:00:00.000Z',
        datos_crudos: null,
    },
    {
        id: 1009,
        titulo: 'QA Engineer Jr. (Automatización)',
        empresa: 'IBM Argentina',
        ubicacion: 'Buenos Aires, Argentina',
        modalidad: 'remoto',
        descripcion: 'QA Engineer Jr. con foco en automatización de pruebas. Selenium, Cypress o Playwright. Conocimientos de SQL básico para validar resultados.',
        url: 'https://www.glassdoor.com.ar/job-listing/1009',
        plataforma: 'glassdoor',
        nivel_requerido: 'junior',
        salario_min: '650000',
        salario_max: '850000',
        moneda: 'ARS',
        estado_evaluacion: 'aprobada',
        razon_evaluacion: 'QA con automatización alineado al perfil del candidato. IBM es un entorno IT/tech compatible con el puesto buscado.',
        porcentaje_match: 71,
        estado_postulacion: 'no_postulado',
        fecha_publicacion: '2026-04-01T12:00:00.000Z',
        fecha_extraccion: '2026-04-02T08:00:00.000Z',
        datos_crudos: null,
    },
    {
        id: 1010,
        titulo: 'Soporte IT / Help Desk Jr.',
        empresa: 'Telecom Argentina',
        ubicacion: 'Buenos Aires, Argentina',
        modalidad: 'presencial',
        descripcion: 'Soporte técnico nivel 1 para empleados internos. Resolución de incidencias, manejo de tickets, conocimientos básicos de redes y sistemas operativos Windows.',
        url: 'https://www.computrabajo.com.ar/ofertas-de-trabajo/oferta-1010',
        plataforma: 'computrabajo',
        nivel_requerido: 'junior',
        salario_min: null,
        salario_max: null,
        moneda: null,
        estado_evaluacion: 'aprobada',
        razon_evaluacion: 'Soporte IT es una de las especialidades del candidato. Telecom es un entorno IT real y compatible con el perfil objetivo.',
        porcentaje_match: 68,
        estado_postulacion: 'no_postulado',
        fecha_publicacion: '2026-03-31T11:00:00.000Z',
        fecha_extraccion: '2026-04-02T08:00:00.000Z',
        datos_crudos: null,
    },

    // ─── POSTULADAS (3) ───────────────────────────────────────────────────────

    {
        id: 1011,
        titulo: 'Desarrollador React Native Jr.',
        empresa: 'PedidosYa',
        ubicacion: 'Buenos Aires, Argentina',
        modalidad: 'remoto',
        descripcion: 'Desarrollador React Native Jr. para app mobile de delivery. Stack: React Native, TypeScript, consume REST APIs. Metodología ágil.',
        url: 'https://www.linkedin.com/jobs/view/1011',
        plataforma: 'linkedin',
        nivel_requerido: 'junior',
        salario_min: '700000',
        salario_max: '950000',
        moneda: 'ARS',
        estado_evaluacion: 'aprobada',
        razon_evaluacion: 'React Native y TypeScript coinciden con el stack del candidato. Empresa tech con crecimiento y cultura de producto.',
        porcentaje_match: 85,
        estado_postulacion: 'cv_enviado',
        fecha_publicacion: '2026-03-28T10:00:00.000Z',
        fecha_extraccion: '2026-04-01T08:00:00.000Z',
        datos_crudos: null,
    },
    {
        id: 1012,
        titulo: 'Automatizador QA Jr. (Playwright / Cypress)',
        empresa: 'Santander Tecnología',
        ubicacion: 'Buenos Aires, Argentina',
        modalidad: 'híbrido',
        descripcion: 'QA Automation Jr. para banca digital. Playwright o Cypress, TypeScript, integración con pipelines CI/CD. Se valora conocimiento de Git.',
        url: 'https://ar.indeed.com/viewjob?jk=1012',
        plataforma: 'indeed',
        nivel_requerido: 'junior',
        salario_min: null,
        salario_max: null,
        moneda: null,
        estado_evaluacion: 'aprobada',
        razon_evaluacion: 'QA automatización y TypeScript coinciden con el perfil. Entorno bancario es IT compatible con el puesto buscado.',
        porcentaje_match: 80,
        estado_postulacion: 'en_proceso',
        fecha_publicacion: '2026-03-25T09:00:00.000Z',
        fecha_extraccion: '2026-04-01T08:00:00.000Z',
        datos_crudos: null,
    },
    {
        id: 1013,
        titulo: 'Desarrollador TypeScript Jr. (Backend Node.js)',
        empresa: 'OLX Group Argentina',
        ubicacion: 'Buenos Aires, Argentina',
        modalidad: 'remoto',
        descripcion: 'Junior Backend Developer para plataforma de clasificados. Node.js, TypeScript, Express, PostgreSQL. Trabajo en equipo ágil con entregas semanales.',
        url: 'https://www.computrabajo.com.ar/ofertas-de-trabajo/oferta-1013',
        plataforma: 'computrabajo',
        nivel_requerido: 'junior',
        salario_min: '600000',
        salario_max: '800000',
        moneda: 'ARS',
        estado_evaluacion: 'aprobada',
        razon_evaluacion: 'Node.js, TypeScript, Express y PostgreSQL están 100% en el stack del candidato. Match muy alto.',
        porcentaje_match: 74,
        estado_postulacion: 'cv_enviado',
        fecha_publicacion: '2026-03-27T13:00:00.000Z',
        fecha_extraccion: '2026-04-01T08:00:00.000Z',
        datos_crudos: null,
    },

    // ─── RECHAZADAS (8) ──────────────────────────────────────────────────────

    {
        id: 1014,
        titulo: 'Desarrollador Java Jr. (Spring Boot)',
        empresa: 'Siemens Argentina',
        ubicacion: 'Buenos Aires, Argentina',
        modalidad: 'presencial',
        descripcion: 'Desarrollador Junior en Java con Spring Boot para microservicios internos. REST, JPA, MySQL.',
        url: 'https://www.bumeran.com.ar/empleos/oferta/1014',
        plataforma: 'bumeran',
        nivel_requerido: 'junior',
        salario_min: null,
        salario_max: null,
        moneda: null,
        estado_evaluacion: 'rechazada',
        razon_evaluacion: 'Rechazada: requiere Java como tecnología principal. Java está explícitamente excluido del perfil del candidato.',
        porcentaje_match: 22,
        estado_postulacion: 'no_postulado',
        fecha_publicacion: '2026-03-30T14:00:00.000Z',
        fecha_extraccion: '2026-04-02T08:00:00.000Z',
        datos_crudos: null,
    },
    {
        id: 1015,
        titulo: 'Senior Frontend Developer (5+ años React)',
        empresa: 'MercadoPago',
        ubicacion: 'Buenos Aires, Argentina',
        modalidad: 'remoto',
        descripcion: 'Senior Frontend Developer con 5+ años de experiencia en React y Redux. Liderazgo técnico de squad. Mentoreo a juniors.',
        url: 'https://www.linkedin.com/jobs/view/1015',
        plataforma: 'linkedin',
        nivel_requerido: 'senior',
        salario_min: '1500000',
        salario_max: '2000000',
        moneda: 'ARS',
        estado_evaluacion: 'rechazada',
        razon_evaluacion: 'Rechazada: requiere perfil Senior con 5+ años de experiencia y liderazgo de equipo. El candidato es trainee/junior.',
        porcentaje_match: 35,
        estado_postulacion: 'no_postulado',
        fecha_publicacion: '2026-04-01T16:00:00.000Z',
        fecha_extraccion: '2026-04-02T08:00:00.000Z',
        datos_crudos: null,
    },
    {
        id: 1016,
        titulo: 'DevOps Engineer Jr. (AWS / Docker)',
        empresa: 'Globant',
        ubicacion: 'Buenos Aires, Argentina',
        modalidad: 'remoto',
        descripcion: 'DevOps Jr. con conocimientos en AWS (EC2, S3, Lambda), Docker, Kubernetes y configuración de CI/CD pipelines.',
        url: 'https://ar.indeed.com/viewjob?jk=1016',
        plataforma: 'indeed',
        nivel_requerido: 'junior',
        salario_min: null,
        salario_max: null,
        moneda: null,
        estado_evaluacion: 'rechazada',
        razon_evaluacion: 'Rechazada: perfil DevOps/Cloud no coincide con el candidato. AWS, Docker y Kubernetes están fuera del stack objetivo.',
        porcentaje_match: 28,
        estado_postulacion: 'no_postulado',
        fecha_publicacion: '2026-03-29T10:00:00.000Z',
        fecha_extraccion: '2026-04-02T08:00:00.000Z',
        datos_crudos: null,
    },
    {
        id: 1017,
        titulo: 'Desarrollador PHP Jr. (Laravel)',
        empresa: 'Empresa de e-commerce',
        ubicacion: 'Buenos Aires, Argentina',
        modalidad: 'híbrido',
        descripcion: 'Desarrollador PHP Jr. con framework Laravel. MySQL, REST APIs, manejo de Git. Se valoran buenas prácticas y trabajo en equipo.',
        url: 'https://www.computrabajo.com.ar/ofertas-de-trabajo/oferta-1017',
        plataforma: 'computrabajo',
        nivel_requerido: 'junior',
        salario_min: null,
        salario_max: null,
        moneda: null,
        estado_evaluacion: 'rechazada',
        razon_evaluacion: 'Rechazada: PHP y Laravel están fuera del stack del candidato. Tecnología no alineada con el perfil objetivo.',
        porcentaje_match: 30,
        estado_postulacion: 'no_postulado',
        fecha_publicacion: '2026-03-31T16:00:00.000Z',
        fecha_extraccion: '2026-04-02T08:00:00.000Z',
        datos_crudos: null,
    },
    {
        id: 1018,
        titulo: 'Analista Programador COBOL',
        empresa: 'Banco Nación',
        ubicacion: 'CABA, Argentina',
        modalidad: 'presencial',
        descripcion: 'Analista Programador en COBOL para sistemas mainframe. Mantenimiento de sistemas legacy bancarios. Turno fijo.',
        url: 'https://www.glassdoor.com.ar/job-listing/1018',
        plataforma: 'glassdoor',
        nivel_requerido: null,
        salario_min: null,
        salario_max: null,
        moneda: null,
        estado_evaluacion: 'rechazada',
        razon_evaluacion: 'Rechazada: COBOL/mainframe son tecnologías legacy fuera del stack. El perfil del candidato es desarrollo web/mobile moderno.',
        porcentaje_match: 10,
        estado_postulacion: 'no_postulado',
        fecha_publicacion: '2026-03-28T08:00:00.000Z',
        fecha_extraccion: '2026-04-02T08:00:00.000Z',
        datos_crudos: null,
    },
    {
        id: 1019,
        titulo: 'Desarrollador Android Jr. (Kotlin)',
        empresa: 'Naranja X',
        ubicacion: 'Córdoba, Argentina',
        modalidad: 'presencial',
        descripcion: 'Desarrollador Android Jr. con Kotlin y Jetpack Compose. Apps nativas, consumo de REST APIs, integración con Firebase.',
        url: 'https://www.linkedin.com/jobs/view/1019',
        plataforma: 'linkedin',
        nivel_requerido: 'junior',
        salario_min: null,
        salario_max: null,
        moneda: null,
        estado_evaluacion: 'rechazada',
        razon_evaluacion: 'Rechazada: Kotlin/Android nativo fuera del stack del candidato. El candidato tiene React Native, no desarrollo Android nativo.',
        porcentaje_match: 25,
        estado_postulacion: 'no_postulado',
        fecha_publicacion: '2026-03-30T09:00:00.000Z',
        fecha_extraccion: '2026-04-02T08:00:00.000Z',
        datos_crudos: null,
    },
    {
        id: 1020,
        titulo: 'DBA SQL Server Sr.',
        empresa: 'IBM Argentina',
        ubicacion: 'Buenos Aires, Argentina',
        modalidad: 'híbrido',
        descripcion: 'DBA SQL Server Senior. Diseño y normalización de schemas, optimización de queries, backup, recovery y alta disponibilidad.',
        url: 'https://www.bumeran.com.ar/empleos/oferta/1020',
        plataforma: 'bumeran',
        nivel_requerido: 'senior',
        salario_min: null,
        salario_max: null,
        moneda: null,
        estado_evaluacion: 'rechazada',
        razon_evaluacion: 'Rechazada: requiere perfil Senior DBA. El candidato tiene conocimientos básicos de SQL, no experiencia como administrador de bases de datos.',
        porcentaje_match: 32,
        estado_postulacion: 'no_postulado',
        fecha_publicacion: '2026-04-01T14:00:00.000Z',
        fecha_extraccion: '2026-04-02T08:00:00.000Z',
        datos_crudos: null,
    },
    {
        id: 1021,
        titulo: 'Lead Developer Full Stack (Tech Lead)',
        empresa: 'Accenture Argentina',
        ubicacion: 'Buenos Aires, Argentina',
        modalidad: 'híbrido',
        descripcion: 'Tech Lead Full Stack con Angular y Node.js. Liderazgo técnico de un equipo de 5+ desarrolladores. Diseño de arquitectura y mentoreo.',
        url: 'https://ar.indeed.com/viewjob?jk=1021',
        plataforma: 'indeed',
        nivel_requerido: 'senior',
        salario_min: '2000000',
        salario_max: '2800000',
        moneda: 'ARS',
        estado_evaluacion: 'rechazada',
        razon_evaluacion: 'Rechazada: requiere liderazgo técnico de equipo y experiencia como Tech Lead. El candidato está en nivel trainee/junior.',
        porcentaje_match: 18,
        estado_postulacion: 'no_postulado',
        fecha_publicacion: '2026-04-02T10:00:00.000Z',
        fecha_extraccion: '2026-04-02T08:00:00.000Z',
        datos_crudos: null,
    },

    // ─── PENDIENTES (4) ──────────────────────────────────────────────────────

    {
        id: 1022,
        titulo: 'Analista Desarrollador Jr. (C# / .NET)',
        empresa: 'Financiadora del Sur',
        ubicacion: 'Buenos Aires, Argentina',
        modalidad: 'híbrido',
        descripcion: 'Analista Desarrollador Jr. para sistemas de gestión financiera. C#, .NET, SQL Server. Trabajo con stakeholders internos.',
        url: 'https://www.linkedin.com/jobs/view/1022',
        plataforma: 'linkedin',
        nivel_requerido: 'junior',
        salario_min: null,
        salario_max: null,
        moneda: null,
        estado_evaluacion: 'pendiente',
        razon_evaluacion: null,
        porcentaje_match: null,
        estado_postulacion: 'no_postulado',
        fecha_publicacion: '2026-04-03T10:00:00.000Z',
        fecha_extraccion: '2026-04-04T08:00:00.000Z',
        datos_crudos: null,
    },
    {
        id: 1023,
        titulo: 'QA Tester Funcional Jr.',
        empresa: 'Empresa SaaS B2B',
        ubicacion: 'Buenos Aires, Argentina',
        modalidad: 'remoto',
        descripcion: 'QA Tester Jr. para plataforma SaaS. Testing funcional, escritura de casos de prueba, reporte de bugs y seguimiento en Jira.',
        url: 'https://www.computrabajo.com.ar/ofertas-de-trabajo/oferta-1023',
        plataforma: 'computrabajo',
        nivel_requerido: 'trainee',
        salario_min: null,
        salario_max: null,
        moneda: null,
        estado_evaluacion: 'pendiente',
        razon_evaluacion: null,
        porcentaje_match: null,
        estado_postulacion: 'no_postulado',
        fecha_publicacion: '2026-04-03T11:00:00.000Z',
        fecha_extraccion: '2026-04-04T08:00:00.000Z',
        datos_crudos: null,
    },
    {
        id: 1024,
        titulo: 'Frontend Developer Angular / React Jr.',
        empresa: 'Startup Fintech',
        ubicacion: 'Buenos Aires, Argentina',
        modalidad: 'remoto',
        descripcion: 'Frontend Jr. para startup fintech en crecimiento. Angular o React, TypeScript, buenas prácticas y colaboración en equipo.',
        url: 'https://www.getonbrd.com/jobs/1024',
        plataforma: 'getonbrd',
        nivel_requerido: 'junior',
        salario_min: '500000',
        salario_max: '700000',
        moneda: 'ARS',
        estado_evaluacion: 'pendiente',
        razon_evaluacion: null,
        porcentaje_match: null,
        estado_postulacion: 'no_postulado',
        fecha_publicacion: '2026-04-04T08:00:00.000Z',
        fecha_extraccion: '2026-04-04T08:00:00.000Z',
        datos_crudos: null,
    },
    {
        id: 1025,
        titulo: 'IT Support Level 1 / Help Desk',
        empresa: 'Empresa logística',
        ubicacion: 'GBA Norte, Argentina',
        modalidad: 'presencial',
        descripcion: 'Soporte técnico nivel 1. Gestión de usuarios y equipos, resolución de incidencias, impresoras y periféricos. Conocimientos básicos de redes.',
        url: 'https://www.bumeran.com.ar/empleos/oferta/1025',
        plataforma: 'bumeran',
        nivel_requerido: 'trainee',
        salario_min: null,
        salario_max: null,
        moneda: null,
        estado_evaluacion: 'pendiente',
        razon_evaluacion: null,
        porcentaje_match: null,
        estado_postulacion: 'no_postulado',
        fecha_publicacion: '2026-04-04T09:00:00.000Z',
        fecha_extraccion: '2026-04-04T08:00:00.000Z',
        datos_crudos: null,
    },
];

// Estadísticas calculadas a partir del array de demo.
export const ESTADISTICAS_DEMO: Estadisticas = {
    total: OFERTAS_DEMO.length,
    pendientes: OFERTAS_DEMO.filter(o => o.estado_evaluacion === 'pendiente').length,
    aprobadas: OFERTAS_DEMO.filter(o => o.estado_evaluacion === 'aprobada').length,
    rechazadas: OFERTAS_DEMO.filter(o => o.estado_evaluacion === 'rechazada').length,
};
